name: Wakhan
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python==3.8
  - samtools>=1.14
  - bcftools>=1.14
  - pysam
  - pyfaidx
  - numpy
  - pandas
  - plotly
  - scikit-learn==1.2.0
  - scipy==1.9.2
  - ruptures
  - pip
  - pip:
    - vcf_parser
    - kaleido