name: Wakhan
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.10
  - setuptools<81
  - samtools>=1.14
  - bcftools>=1.14
  - pysam
  - pyfaidx
  - numpy<1.26.0
  - pandas
  - plotly
  - scikit-learn==1.2.0
  - scipy==1.9.2
  - ruptures
  - intervaltree
  - pip
  - matplotlib-base
  - pip:
    - vcf_parser
    - kaleido
